### ISSUE TITLE
Backspace during task entry in timetrack.py prints '\x08'

### ISSUE THREAD

**Issue by japanjeff** [waynew/whelps#1]
Running timetrack.py in cmd or powershell in Windows 7 with Python 3.5.2, if you try to press backspace when entering a task title, it prints `'\x08'` on a new line and then prints the "time - task: title entry" over again. After typing "Testing" and pressing backspace, the screen looks like this:

```
00:00:02 - Task: Testing
'\x08'
00:01:38 - Task: Testing
```

**Comment by waynew** [comment]
Part of this is intentional - namely it doesn't recognize that character so it prints it out. That being said apparently there a multiple backspace characters ;)

**Comment by waynew** [comment]
I think it's fixed, but apparently I'm having a hard time pushing changes out to github? Not sure why 😕
